name: assignment_pay
description: A new Flutter application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  flutter_svg: ^1.0.3
  get: ^4.6.1
  image_cropper: ^2.0.0
  image_picker: ^0.8.5
  intl: ^0.17.0
  pin_code_fields: ^7.4.0
  shared_preferences: ^2.0.13
  url_launcher: ^6.1.0
  fluttertoast: ^8.0.9
  firebase_core: ^1.16.0
  firebase_messaging: ^11.3.0
  awesome_notifications: ^0.6.21
  place_picker: ^0.9.20-nullsafety
  flutter_staggered_animations: ^1.0.0
  key_guardmanager: ^1.0.0
  local_auth: ^2.1.2
  pull_to_refresh: ^2.0.0
  flip_card: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  intl_utils: ^2.6.1
dependency_overrides:
  firebase_core_platform_interface: 4.5.1
# flutter_launcher_icons: ^0.9.0
# flutter_icons:
#   android: "ic_launcher"
#   ios: true
#   image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Gilory
      fonts:
        - asset: assets/fonts/Gilroy-Regular.otf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.otf
          weight: 500
        - asset: assets/fonts/Gilroy-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Gilroy-Bold.otf
          weight: 700
#flutter_intl:
#  enabled: true
