name: ausicare_doctor
description: A new Flutter application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.0.0
  carousel_slider: ^3.0.0
  cupertino_icons: ^1.0.3
  device_info: ^2.0.0
  dio: ^4.0.0
  file_picker: ^3.0.1
  firebase_messaging: ^9.1.3
  flutter_facebook_login: ^3.0.0
  flutter_google_places: ^0.3.0
  flutter_local_notifications: ^5.0.0+4
  flutter_svg: ^0.22.0
  geolocator: ^7.0.3
  get: ^4.1.4
  google_sign_in: ^5.0.2
  image_cropper: ^1.4.0
  image_picker: null
  intl: ^0.17.0
  location: null
  permission_handler: ^7.1.0
  pin_code_fields: ^7.1.0
  shared_preferences: ^2.0.5
  sign_in_with_apple: ^3.0.0
  url_launcher: ^6.0.2
  sms_autofill: ^2.0.0

#dependency_override:
#  http_parser: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.2.0

#   flutter_launcher_icons: ^0.9.0
# flutter_icons:
#   android: "ic_launcher"
#   ios: true
#   image_path: "assets/icons/logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Sf-Pro-Display
      fonts:
        - asset: assets/fonts/Sf-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/Sf-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/Sf-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/Sf-Pro-Display-Bold.otf
          weight: 700
flutter_intl:
  enabled: true
