name: flutter_mobile_template
description: A new Flutter application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  flutter_svg: ^1.0.3
  get: ^4.6.1
  image_cropper: ^1.5.0
  image_picker: ^0.8.4+9
  intl: ^0.17.0
  pin_code_fields: ^7.3.0
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  fluttertoast: ^8.0.8
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6
  awesome_notifications: ^0.6.21

#dependency_override:
#  http_parser: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  intl_utils: ^2.6.1
# flutter_launcher_icons: ^0.9.0
# flutter_icons:
#   android: "ic_launcher"
#   ios: true
#   image_path: "assets/icons/logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Gilory
      fonts:
        - asset: assets/fonts/Gilroy-Regular.otf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.otf
          weight: 500
        - asset: assets/fonts/Gilroy-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Gilroy-Bold.otf
          weight: 700
#flutter_intl:
#  enabled: true
