name: flutter_mobile_template
description: A new Flutter application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^2.5.1
  cupertino_icons: ^1.0.2
  dio: ^3.0.10
  file_picker: ^3.0.0
  firebase_messaging: ^9.0.0
  flutter_facebook_login: ^3.0.0
  flutter_google_places: ^0.2.8
  flutter_svg: ^0.19.3
  #? geolocation: ^1.1.2
  get: ^4.0.0-nullsafety.2
  google_sign_in: ^5.0.1
  image_cropper: ^1.4.0
  image_picker: null
  intl: ^0.17.0
  permission_handler: ^6.1.1
  pin_code_fields: ^7.0.0
  qr_code_scanner: ^0.4.0-nullsafety.0
  shared_preferences: ^2.0.5
  sign_in_with_apple: ^2.5.4
  url_launcher: ^6.0.2

dependency_override:
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
#   flutter_launcher_icons: ^0.9.0
# flutter_icons:
#   android: "ic_launcher"
#   ios: true
#   image_path: "assets/icons/logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Grandstander
      fonts:
        - asset: assets/fonts/Grandstander-Thin.ttf
          weight: 100
        - asset: assets/fonts/Grandstander-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Grandstander-Light.ttf
          weight: 300
        - asset: assets/fonts/Grandstander-Regular.ttf
          weight: 400
        - asset: assets/fonts/Grandstander-Medium.ttf
          weight: 500
        - asset: assets/fonts/Grandstander-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Grandstander-Bold.ttf
          weight: 700
        - asset: assets/fonts/Grandstander-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Grandstander-Black.ttf
          weight: 900
flutter_intl:
  enabled: true
